version: 2

sources:
  - name: mercurymart
    database: RAW
    schema: DBT_PGANDHI

    tables:
      - name: raw_orders
      - name: raw_order_items
      - name: raw_customers
      - name: raw_products
      - name: raw_payments
      - name: raw_refunds
      - name: raw_web_events
      - name: raw_web_sessions
      - name: raw_marketing_campaigns
      - name: raw_coupons
      - name: raw_inventory_snapshots
      - name: raw_suppliers
